server.port=8083

# DATABASE
spring.datasource.url=jdbc:mysql://localhost/microservices3
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
